### ISSUE TITLE
Is this really safe with cookie-based session?

### ISSUE THREAD

**Issue by zhaoxin** [maxcountryman/flask-seasurf#58]
Flask is using cookie-based session, so is it safe to implement anti-CSRF this way?

**Comment by maxcountryman** [comment]
I'm not really sure what your concern here is.

**Comment by alanhamlett** [comment]
@zhaoxin yes, the Flask session cookie is signed with your application secret so it can not be changed by anyone except your Flask server. The point of a CSRF token is to prevent other domains from submitting POST requests to your domain, because the browser does not let other domains read cookies on your domain.
